openapi: 3.0.0
info:
  title: POC API - hana_mta_api
  description: Test API for HANA Multi Target Application Environment.
  version: 1.0.0
servers:
  - url: https://b22fc7a6trial-dev-hana-mta-api-srv.cfapps.eu10.hana.ondemand.com/
    description: Main Endpoint.

paths:
  /:
    get:
      summary: Returns a list of error logs.
      description: Returns a list of errors.
      responses:
        '200':    # status code
          description: A JSON array of error log
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  errorNumber:
                    type: string
                  objectName:
                    type: string
                  processId:
                    type: integer
                  createdon:
                    type: string
                  errorMessage:
                    type: string
                    
    post:
      summary: Inserts an error log.
      description: Inserts a list of errors.
      responses:
        '200':    # status code
          description: A JSON updated error log
          content:
            application/json:
              schema:
                type: object
                properties:
                  errorNumber:
                    type: string
                  objectName:
                    type: string
                  processId:
                    type: integer
                  errorMessage:
                    type: string
                    
    put:
      summary: Updates a error log.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                id:
                  type: string
                errorNumber:
                  type: string
                objectName:
                  type: string
                processId:
                  type: integer
                errorMessage:
                  type: string  
      description: Updates a error log.
      responses:
        '200':    # status code
          description: Status and number of affected rows
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                  Affected rows:
                    type: string
    
  /{id}:
    get:
      summary: Returns an error log.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the log to get.
          schema:
            type: string
            minimum: 1
      description: Returns an error log.
      responses:
        '200':    # status code
          description: A JSON with an error log
          content:
            application/json:
              schema:
                type: object
                properties:
                  id:
                    type: string
                  errorNumber:
                    type: string
                  objectName:
                    type: string
                  processId:
                    type: integer
                  createdon:
                    type: string
                  errorMessage:
                    type: string
  
    delete:
      summary: Deletes a error log.
      parameters:
        - name: id
          in: path
          required: true
          description: The ID of the log to be deleted.
          schema:
            type: string
            minimum: 1
      description: Deletes a error log.
      responses:
        '200':    # status code
          description: Status and number of affected rows
          content:
            application/json:
              schema:
                type: object
                properties:
                  Status:
                    type: string
                  Affected rows:
                    type: string
